baseURL = "https://tpl.as.cornell.edu"
languageCode = "en-us"
title = "Cornell Tech Policy Lab"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "People"
url = "/people/"
weight = 1

[[menu.main]]
name = "Activities"
url = "/activities/"
weight = 2

[[menu.main]]
name = "Research"
url = "/research/"
weight = 3

[[menu.main]]
name = "Media"
url = "/media/"
weight = 4