backend:
  name: git-gateway
  branch: master
media_folder: "/static/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media"
collections:
  - name: "research"
    label: "Research"
    create: true
    folder: "content/research/"
    title: "research"
    identifier_field: "title"
    editor:
      preview: false
    filter: {field: "cms_visible", value: true}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Date Override", name: "dateOverride", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Visible", name: "cms_visible", widget: hidden, default: true}
  - name: "media"
    label: "Media"
    create: true
    folder: "content/media/"
    title: "media"
    identifier_field: "title"
    editor:
      preview: false
    filter: {field: "cms_visible", value: true}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Date Override", name: "dateOverride", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Visible", name: "cms_visible", widget: hidden, default: true}
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: "Browser Title", name: supertitle, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Description, name: description, widget: text}
          - { label: 'Body', name: 'body', widget: 'markdown' }